// ##############################
// // // data for populating the calendar in Calendar view
// #############################

var today = new Date();
var y = today.getFullYear();
var m = today.getMonth();
var d = today.getDate();

const days = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

const academicCourses = [
  {
    id: 1,
    title: "Algorithms",
    start: new Date(2021, 10, 24, 12),
    end: new Date(2021, 10, 24, 14),
    day: days[new Date(2021, 10, 24, 12).getDay()],
    semester: "A",
    lecturer: "Dr. Iris",
    degree: "Computer Science",
  },
  {
    id: 2,
    title: "Advanced Programming",
    start: new Date(2021, 10, 24, 15),
    end: new Date(2021, 10, 24, 16, 30),
    day: days[new Date(2021, 10, 24, 12).getDay()],
    semester: "A",
    lecturer: "Dr. Smuel",
    degree: "Computer Science",
  },
  {
    id: 3,
    title: "Logic",
    start: new Date(2021, 10, 25, 12),
    end: new Date(2021, 0, 25, 10, 30),
    day: days[new Date(2021, 10, 25, 12).getDay()],
    semester: "A",
    lecturer: "Dr. Zack",
    degree: "Computer Science",
  },
  {
    id: 4,
    title: "Logic",
    start: new Date(2021, 2, 14, 12),
    end: new Date(2021, 2, 8, 14, 30),
    day: days[new Date(2021, 2, 14, 12).getDay()],
    semester: "B",
    lecturer: "Dr. Zack",
    degree: "Computer Science",
  },
];

const events = [
  {
    eventId: 4,
    title: "All Day Event",
    creator: null,
    invitees: [],
    start: new Date(y, m, 1),
    end: new Date(y, m, 1),
    description: "tryyy",
    address: "MTA",
    allDay: true,
    repeat: "none",
    color: null,
  },
  {
    eventId: 2,
    title: "Meeting",
    creator: null,
    invitees: [],
    start: new Date(y, m, d - 1, 10, 30),
    end: new Date(y, m, d - 1, 11, 30),
    description: null,
    address: "MTA",
    allDay: false,
    repeat: "none",
    color: "green",
  },
  {
    eventId: 2,
    title: "Checking events side bar",
    creator: null,
    invitees: [],
    start: new Date(y, m, d, 10, 30),
    end: new Date(y, m, d, 11, 30),
    description: null,
    address: null,
    allDay: false,
    repeat: "none",
    color: "green",
  },
  {
    eventId: 2,
    title: "Lunch",
    creator: null,
    invitees: [],
    start: new Date(y, m, d + 7, 12, 0),
    end: new Date(y, m, d + 7, 14, 0),
    description: "Aroma Salad",
    address: null,
    allDay: false,
    repeat: "none",
    color: "orange",
  },
  {
    eventId: 2,
    title: "BD-PRO-REACT Launch",
    creator: null,
    invitees: [],
    start: new Date(y, m, d - 2),
    end: new Date(y, m, d - 2),
    description: "",
    address: null,
    allDay: true,
    repeat: "none",
    color: "azure",
  },
  {
    eventId: 2,
    title: "Birthday Party",
    creator: null,
    invitees: [],
    start: new Date(y, m, d + 1, 19, 0),
    end: new Date(y, m, d + 1, 22, 30),
    description: "Tali`s B-day",
    address: "Ha turmus 30",
    allDay: false,
    repeat: "none",
    color: "yellow",
  },
  {
    eventId: 2,
    title: "Click for Creative Tim",
    creator: null,
    invitees: [],
    start: new Date(y, m, 21),
    end: new Date(y, m, 22),
    description: "",
    address: "",
    allDay: false,
    repeat: "none",
    color: "orange",
  },
  {
    eventId: 2,
    title: "Click for Google",
    creator: null,
    invitees: [],
    start: new Date(y, m, 21),
    end: new Date(y, m, 22),
    description: "stammmm",
    address: "",
    allDay: false,
    repeat: "none",
    color: "red",
  },
  {
    eventId: 0,
    title: "Homework",
    creator: "shiraz@mta.ac.il",
    invitees: ["ronen@mta.ac.il", "chenlu@mta.ac.il"],
    start: new Date(y, m, 12),
    end: new Date(y, m, 13),
    description: "Working on C# final project",
    address: "",
    allDay: false,
    repeat: "daily",
    color: "invite",
  },
];

const notifications = [
  {
    eventId: 0,
    title: "Homework",
    creator: "shiraz@mta.ac.il",
    invitees: ["ronen@mta.ac.il", "chenlu@mta.ac.il"],
    start: new Date(2021, 9 - 1, 10, 21, 0),
    end: new Date(2021, 12 - 1, 11, 10, 0),
    description: "Working on C# final project",
    address: "",
    allDay: false,
    repeat: "daily",
    color: null,
  },
  {
    eventId: 1,
    title: "study to exam",
    creator: "moshedir@mta.ac.il",
    invitees: [],
    start: new Date(2021, 1 - 1, 3, 21, 0),
    end: new Date(2021, 4 - 1, 2, 10, 0),
    description: "",
    address: "your house",
    allDay: false,
    repeat: "none",
    color: null,
  },
  {
    eventId: 2,
    title: "חדואאאאא בעעעעעע",
    creator: "hanamami@mta.ac.il",
    invitees: ["ronen@mta.ac.il", "chenlu@mta.ac.il"],
    start: new Date(2021, 5 - 1, 5, 21, 0),
    end: new Date(2021, 10 - 1, 12, 10, 0),
    description: "חדוא א' הכנה למבחן",
    address: "MTA",
    allDay: false,
    repeat: "monthly",
    color: null,
  },
];

const generalDetails = [
  {
    userName: "Shirazvi",
    email: "shirazvi@mta.ac.il",
    firstName: "Shiraz",
    lastName: "Viner",
    address: "Ha Turmus",
    city: "Rishon Le Zion",
    country: "Israel",
    password: "123456",
    imgUrl: "lora.jpg",
  },
];

export { academicCourses };
export { generalDetails };
export { notifications };
export { events };
